Repository saving-satoshi/saving-satoshi, pull requests merged in 2023-03, with the labels that each got.

#265 Ensure window is defined for useMediaQuery
  hooks/useMediaQuery.ts
Labels: ready for review

#212 Change background color for modals
  components/Modals/Login.tsx
  components/Modals/SignUp.tsx
  tailwind.config.js
Labels: ready for review

#263 Copy updates on various pages
  content/chapters/chapter-1/index.tsx
  content/introductions/reaping-rewards/index.tsx
  content/lessons/genesis/genesis-1/index.tsx
  content/lessons/genesis/genesis-2/index.tsx
  content/lessons/transacting/transacting-1/index.tsx
  content/lessons/transacting/transacting-2/index.tsx
  content/lessons/transacting/transacting-3/index.tsx
  i18n/locales/en/translations.ts
  public/assets/images/chapter-1-cover.jpg
  public/assets/images/chapter-1-finish.jpg
  public/assets/images/chapter-1-intro-1.jpg
  public/assets/images/chapter-2-cover.jpg
  ui/chapter/End.tsx
  ui/common/CodeExample.tsx
  ui/common/Title.tsx
  ui/common/Tooltip.tsx
  ui/introduction/Introduction.tsx
Labels: ready for review

#274 Second Intro for Chapter 1
  .vscode/settings.json
  content/chapters/chapter-1/index.tsx
  content/lessons/holocat/index.tsx
  content/lessons/index.tsx
  i18n/locales/en/translations.ts
  public/assets/images/chapter-1-holocat.jpg
  ui/introduction/Introduction.tsx
  ui/introduction/IntroductionLayout.tsx
  ui/introduction/index.ts
Labels: ready for review

#277 NavBar Link keeps styling in mobile
  components/Navbar/NavbarMobile/NavbarMobile.tsx
Labels: ready for review

#266 Introduce the new Outro page for Chapter-1
  content/chapters/chapter-1/index.tsx
  content/lessons/genesis/genesis-1/index.tsx
  content/lessons/genesis/genesis-4/index.tsx
  content/lessons/index.tsx
  content/lessons/transacting-4/index.tsx
  content/lessons/transacting/transacting-3/index.tsx
  i18n/locales/en/translations.ts
  public/assets/images/chapter-1-outro.jpg
  ui/common/TextImageLayout.tsx
  ui/common/index.ts
  ui/introduction/Introduction.tsx
  ui/introduction/index.ts
Labels: ready for review

#279 Further simplifications to translation system
  .vscode/settings.json
  app/[lang]/chapters/[slug]/[lesson]/layout.tsx
  app/[lang]/chapters/[slug]/layout.tsx
  content/chapters/chapter-1/index.tsx
  content/introductions/reaping-rewards/index.tsx
  content/lessons/chapter-1/outro-1.tsx
  content/lessons/chapter-1/outro-2.tsx
  content/lessons/index.tsx
  content/lessons/transacting/transacting-3/index.tsx
  i18n/locales/en.ts
  i18n/locales/en/index.ts
  i18n/locales/index.ts
  i18n/locales/nl.ts
  i18n/locales/nl/index.ts
  lib/translate.tsx
  ui/chapter/Chapter.tsx
Labels: ready for review

#280 Refactor lesson structure to allow for multiple intros
  app/[lang]/about/page.tsx
  app/[lang]/chapters/[slug]/[lesson]/page.tsx
  app/[lang]/chapters/[slug]/page.tsx
  app/[lang]/chapters/page.tsx
  app/page.tsx
  components/Footer.tsx
  components/Navbar/Address.tsx
  components/Navbar/NavbarDesktop/NavbarDesktop.tsx
  components/Navbar/NavbarDesktop/TabGroup.tsx
  components/Navbar/NavbarMobile/NavbarMobile.tsx
  components/Navbar/NavbarMobile/TabGroupMobile.tsx
  components/Topbar.tsx
  config/index.ts
  config/sections.ts
  config/site.ts
  content/chapters/chapter-1/index.tsx
  content/chapters/chapter-10/index.tsx
  content/chapters/chapter-2/index.tsx
  content/chapters/chapter-3/index.tsx
  content/chapters/chapter-4/index.tsx
  content/chapters/chapter-5/index.tsx
  content/chapters/chapter-6/index.tsx
  content/chapters/chapter-7/index.tsx
  content/chapters/chapter-8/index.tsx
  content/chapters/chapter-9/index.tsx
  content/index.ts
  content/introductions/index.tsx
  content/lessons/chapter-1/genesis-1.tsx
  content/lessons/chapter-1/genesis-2.tsx
  content/lessons/chapter-1/genesis-3.tsx
  content/lessons/chapter-1/genesis-4.tsx
  content/lessons/chapter-1/index.ts
  content/lessons/chapter-1/intro-1.tsx
  content/lessons/chapter-1/intro-2.tsx
  content/lessons/chapter-1/outro-1.tsx
  content/lessons/chapter-1/transacting-1.tsx
  content/lessons/chapter-1/transacting-2.tsx
  content/lessons/chapter-1/transacting-3.tsx
  content/lessons/index.tsx
  hooks/index.ts
  hooks/useContentRoute.ts
  hooks/useLocalizedRoutes.ts
  hooks/usePathData.ts
  i18n/locales/en.ts
  lib/content.ts
  types/index.ts
  ui/chapter/ChallengeList.tsx
  ui/chapter/Chapter.tsx
  ui/introduction/Introduction.tsx
  ui/lesson/TerminalChallenge.tsx
Labels: question, ready for review

#293 Allow terminal answer with extra whitespace to be marked correctly
  .vscode/settings.json
  ui/lesson/TerminalChallenge.tsx
Labels: ready for review

#294 Update copy for Ch1. challenge 1 pt 2.
  i18n/locales/en.ts
Labels: ready for review

#300 Fix Enter key behavior on Input
  ui/common/Input.tsx
Labels: ready for review

#304 Chapter 1, Challenge 2: Tweak block explorer link
  i18n/locales/en.ts
Labels: question

#305 Accept Double and Single quotes in Terminal Challenge
  ui/lesson/TerminalChallenge.tsx
Labels: ready for review

#306 Update commonError for Transacting-3
  content/lessons/chapter-1/transacting-3.tsx
  i18n/locales/en.ts
Labels: ready for review
